# Generated by Django 6.0 on 2025-12-24 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('guests_max', models.PositiveSmallIntegerField(default=2)),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_terrace', models.BooleanField(default=False)),
                ('forest_view', models.BooleanField(default=True)),
                ('price_per_night_pln', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cover_image_path', models.CharField(blank=True, help_text='Example: infinitivacation/img/apt-1.jpg or static path: infiniti_vacation/img/slide-1.jpg', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='infiniti_va_is_acti_506f24_idx'), models.Index(fields=['slug'], name='infiniti_va_slug_12e65f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('kind', models.CharField(choices=[('booking', 'Booking'), ('block', 'Block (maintenance)')], default='booking', max_length=16)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='infiniti_vacation.apartment')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['apartment', 'start_date', 'end_date'], name='infiniti_va_apartme_2957db_idx'), models.Index(fields=['status'], name='infiniti_va_status_83641a_idx'), models.Index(fields=['kind'], name='infiniti_va_kind_f77e9d_idx')],
            },
        ),
    ]
